config/routes.rb
ShimanoFishNetwork::Application.routes.draw do

  get "contests/index"

  devise_for :dealers

  get "post_tags/index"

  mount Ckeditor::Engine => '/ckeditor'

  get "posts/show"

  root :to => 'home#index'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  def get_or_post(path, opts={}, &block)
    get(path, opts, &block)
    post(path, opts, &block)
  end

  get 'download' => 'home#download'
  
  
  namespace "admin" do
    root :to => 'data_manipulations#index'
    resources :data_manipulations, :only => [:index, :show, :create]
  end

  
  get '/dealers' => 'dealer#index'
  get '/dealers/dl' => 'dealer#download', as: :dealer_download
  post '/api/store_contest' => 'home#store_contest'
  get '/import_campaign' => 'home#import'
  get '/clean_p' => 'home#clean_p'
  get 'upload' => 'catalog#index'
  post 'upload' => 'catalog#create', :as => 'data_manipulations'
  get 'products/suggest' => 'products#suggest', :as => 'product_suggest'
  get 'shimano-shop' => 'stores#index', :as => 'store_locator'
  get 'shimano-shop/suggest' => 'stores#suggest', :as => 'store_suggest'
  get 'shimano-shop/regions' => 'stores#regions', :as => 'store_locator_regions'
  get 'shimano-shop/provinces' => 'stores#provinces', :as => 'store_locator_provinces'
  get 'shimano-shop/cities' => 'stores#cities', :as => 'store_locator_cities'
  get 'shimano-shop/:specialist' => 'stores#specialist'
  get 'cataloghi-shimano' => 'press#index'
  get 'concorso' => 'contests#home'
  get 'concorso/gioca' => 'contests#play'
  get 'concorso/gioca/risultato' => 'contests#result'
  get 'concorso/premi' => 'contests#prizes'
  get '/product_list' => 'products#list'
  get '/products_dealers' => 'products#dealer'
  get '/green-line'      => 'contests#index', as: :contest
  get '/green-line/:id'      => 'contests#vote'
  get '/blog' => 'posts#index'
  scope '/blog' do 
    get '/category/:slug' => 'posts#category'
    get '/tag/:url' => 'posts#tag'
    get '/:date/:title' => 'posts#show', :as => :post_show
    get '/:year/:day/:month/:title' => 'posts#show'
  end
  scope '/community' do
    get '/' => 'communities#index', :as => :community
    get '/riserva' => 'events#reserve', :as => :reserve
    scope '/eventi' do
      get '/' => 'events#index', :as => :events
      get '/archive' => 'events#archive', :as => :events_archive
      get '/(:title)--(:id)' => 'events#show', :as => :event
      get '/(:title)--(:id)/list' => 'events#list', :as => :event_list
      get '/(:title)--(:id)/attend' => 'events#attend', :as => :attend_event
    end
    scope '/galleria' do
      get '/' => 'galleries#index', :as => :galleries
      get '/:id' => 'galleries#show', :as => :gallery
      get '/:gallery_id/foto/:id' => 'photos#show', :as => :photo
      post '/:gallery_id/photos/:id' => 'photos#like', :as => :like_photo
    end
    scope '/galleries' do
      match "/", to: redirect('/galleria')
      match "/:id", to: redirect('/%{id}')
      match '/:gallery_id/photo/:id', to: redirect('/%{gallery_id}/foto/%{id}')
    end
  end

  match '/community/ask-shimano', to: redirect('/ask-shimano'), :status => 301
  match '/community/ask-shimano/*params', to: redirect {|params| "/ask-shimano/#{CGI::unescape(params[:params])}" }, :status => 301

  scope '/garanzia/ask-shimano' do

   
      get '/' => 'question_categories#index', :as => :ask_shimano
      get '/mondo-artificiali/(*params)', to: redirect {|params| "/ask-shimano/tecniche-e-attrezzatura/#{CGI::unescape(params[:params])}" }, :status => 301
      get '/attrezzatura/(*params)', to: redirect {|params| "/ask-shimano/tecniche-e-attrezzatura/#{CGI::unescape(params[:params])}" }, :status => 301
      get '/tecniche-di-pesca/(*params)', to: redirect {|params| "/ask-shimano/tecniche-e-attrezzatura/#{CGI::unescape(params[:params])}" }, :status => 301
      get '/search' => 'questions#search', :as => :search_questions_path
      get '/:category_url(/:subcategory_url)' => 'questions#index', :as => :questions
      get '/:category_url/new-question/expert' => 'questions#expert', :as => :new_expert
      get '/:category_url(/:subcategory_url/)new-question/' => 'questions#new', :as => :new_question
      post '/:category_url' => 'questions#create'
      get '/:category_url/:subcategory_url/:id' => 'questions#show', :as => :question
      post '/:category_url/:subcategory_url/:id/like-answer/:answer_id' => 'questions#like_answer', :as => :like_question_answer
      post '/:category_url/:subcategory_url/:id/send-answer' => 'questions#create_answer', :as => :question_answer
  end

  

  match "/catalogo", to: redirect('/attrezzatura-pesca')
  match "/cataloghi", to: redirect('/cataloghi-shimano')

  scope '/catalogo' do
    match "/", to: redirect('/attrezzatura-pesca')
    match '/:product_type/', to: redirect('/attrezzatura-pesca/%{product_type}')
    match '/:product_type/:product_family', to: redirect('/attrezzatura-pesca/%{product_type}/%{product_family}/')
    match '/:product_type/:product_family/:product_url', to: redirect('/attrezzatura-pesca/%{product_type}--%{product_url}/')
    get '/:product_type/:product_family/tags/(*tags)', to: redirect("/attrezzatura-pesca/%{product_type}/%{product_family}/tags/%{tags}")
  end

  get '/dealers' => 'dealers#index'
  get '/dealers/new' => 'dealers#new'
  get '/dealers/:id' => 'dealers#show'
  post '/dealers/new' => 'dealers#create', as: :dealer_assistance_requests

  match "/attrezzatura-pesca" => 'product_finder#index'

  scope '/attrezzatura-pesca' do
    get '/trova/' => 'product_finder#index'
    get '/trova/*slug' => 'product_finder#index'
    get '/*das', to: redirect('/attrezzatura-pesca')
  end

  get '/tags' => 'tags#index'
  get '/posttags' => 'post_tags#index'

  scope "/garanzia"  do

    devise_for :fishers, :path => '', :skip => [:registrations], :controllers => { :sessions => 'fishing_club/sessions', :confirmations => 'fishing_club/confirmations', :passwords => 'fishing_club/passwords'}
    devise_scope :fisher do
    get 'pro-staff' => 'prostaff#index', :as =>   'pro_staff'
    get 'pro-staff/:url' => 'prostaff#show', :as => 'show_pro_staff'
    get 'prodotti' => 'fishing_club/fishing_club#product'
    get 'eventi' => 'fishing_club/fishing_club#events'
    get "modifica-dati-personali" => "fishing_club/registrations#edit", :as => 'edit_fisher_registration'
      get "cancella" => "fishing_club/registrations#cancel", :as => 'cancel_fisher_registration'
      delete "cancella-iscrizione" => 'fishing_club/registrations#destroy', :as => 'destroy_fisher_registration'
      post "/" => "fishing_club/registrations#create", :as => 'fisher_registration'
      put "/" => "fishing_club/registrations#update"
      post "/" => "fishing_club/registrations#destroy"
      get "registrati" => "fishing_club/registrations#new", :as => 'new_fisher_registration'
    end
    resources :photos, :controller => 'fishing_club/photos', :only => [:new, :create]
    resources :product_registrations, :controller => 'fishing_club/product_registrations', :only => [:index, :new, :create, :show, :update, :edit] do
      collection do
        post 'confirm'
      end
    end
    get '/' => 'fishing_club/fishing_club#index', :as => 'fishing_club'
  end

  get '/:page' => 'pages#show'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :photos
  
  validates :title, :description, :presence => true

  def cover
    self.photos.cover
  end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::AdminController
  inherit_resources

  def create
    create!(:notice => 'Galleria creata con successo!'){ admin_galleries_path }
  end

  protected
  def collection
    @q = end_of_association_chain.search(params[:q])
    @galleries ||= @q.result(:distinct => true).paginate(:page => params[:page])
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def show
    if params[:id].present?
      @gallery = Gallery.find(params[:id])
    else
      @gallery = Gallery.order('created_at DESC').limit(1).first
    end
    @page_title = "Le foto della community"
    @meta_description = "Diventa protagonista della nostra community caricando le foto delle tue catture con attrezzatura Shimano, Loomis e Rapala"
  end
  
  def index
    @galleries = Gallery.order('created_at DESC')
    @page_title = "Le foto della community"
    @meta_description = "Diventa protagonista della nostra community caricando le foto delle tue catture con attrezzatura Shimano, Loomis e Rapala"
  end

end

app/views/admin/galleries/_form.html.erb
<%= f.input :title %>
<%= f.input :description %>

<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "Salva") %> <%= "Salva" %>
  </button>
  <span class="text_button_padding">o</span>
	<%= link_to "Annulla", admin_galleries_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/galleries/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "Lista", admin_galleries_path  %></li>
      <li class="active"><%= link_to "Modifica", edit_admin_gallery_path(@gallery) %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title">Modifica Galleria</h2>
    <div class="inner">
      <%= simple_form_for [:admin, @gallery] do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/admin/galleries/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to 'Lista', admin_galleries_path  %></li>
      <li><%= link_to 'Nuova', new_admin_gallery_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title">Lista Gallerie</h2>
    <%= search_form_for @q, :url => admin_galleries_path do |f| %>
      <%= f.label :title_or_description_cont %>
      <%= f.text_field :title_or_description_cont %>
      <%= f.submit %>
    <% end %>
    <% unless @galleries.empty? %>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>Titolo</th>
          <th>Descrizione</th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @galleries.each do |gallery| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= gallery.id %></td>
          <td><%= link_to gallery.title, edit_admin_gallery_path(gallery) %></td>
          <td><%=truncate gallery.description %></td>
          <td class="last">
            <%= link_to "Visualizza", admin_gallery_path(gallery) %> |
            <%= link_to "Modifica", edit_admin_gallery_path(gallery) %> |
            <%= link_to "Elimina", admin_gallery_path(gallery), :method => :delete, :confirm => "Sei sicuro?" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        <%= will_paginate @galleries %>
      </div>
    </div>
    <% else %>
    <p>Nessuna gallery da visualizzare</p>
    <% end %>
  </div>
</div>

app/views/admin/galleries/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "Lista", admin_galleries_path  %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title">Nuova Galleria</h2>
    <div class="inner">
      <%= simple_form_for [:admin, @gallery] do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

app/views/admin/galleries/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "Lista", admin_galleries_path  %></li>
      <li><%= link_to 'Nuova', new_admin_gallery_path %></li>
      <li><%= link_to 'Modifica', edit_admin_gallery_path(@gallery) %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title">Galleria <%= @gallery.id %></h2>
    <div class="inner">
      <p><b>Titolo: </b><%= @gallery.title %></p>
      <p><b>Descrizione: </b><%= @gallery.description %></p>
      <% unless @gallery.photos.empty? %>
        <h3>Foto della galleria</h3>
        <table class="table">
          <tr>
            <th>Utente</th>
            <th>Titolo</th>
            <th>Descrizione</th>
            <th>Stato</th>
            <th></th>
          </tr>
          <% @gallery.photos.order('published DESC, created_at DESC').each do |photo| %>
            <tr>
              <td><%= link_to photo.fisher.complete_name, admin_fisher_path(photo.fisher) %></td>
              <td><%= photo.title %></td>
              <td><%= photo.description %></td>
              <td><%= photo.published? ? 'Approvata' : 'Non approvata' %></td>
              <td>
                <%= link_to 'Moderazione', edit_admin_gallery_photo_path(@gallery, photo) %>
                <% unless photo.published? %>
                  | <%= link_to 'Approva', publish_admin_gallery_photo_path(@gallery, photo), :method => :post, :confirm => 'Sei sicuro di voler approvare questa foto?' %> |
                  <%= link_to 'Rifiuta', admin_gallery_photo_path(@gallery, photo), :method => :delete, :confirm => "Sei sicuro di voler rifiutare questa foto? L'operazione non è reversibile." %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      <% else %>
        <h3>Nessuna foto caricata per questa galleria</h3>
      <% end %>
    </div>
  </div>
</div>