config/routes.rb
ShimanoFishNetwork::Application.routes.draw do

  get "contests/index"

  devise_for :dealers

  get "post_tags/index"

  mount Ckeditor::Engine => '/ckeditor'

  get "posts/show"

  root :to => 'home#index'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  def get_or_post(path, opts={}, &block)
    get(path, opts, &block)
    post(path, opts, &block)
  end

  get 'download' => 'home#download'
  
  
  namespace "admin" do
    root :to => 'data_manipulations#index'
    resources :data_manipulations, :only => [:index, :show, :create]
  end

  
  get '/dealers' => 'dealer#index'
  get '/dealers/dl' => 'dealer#download', as: :dealer_download
  post '/api/store_contest' => 'home#store_contest'
  get '/import_campaign' => 'home#import'
  get '/clean_p' => 'home#clean_p'
  get 'upload' => 'catalog#index'
  post 'upload' => 'catalog#create', :as => 'data_manipulations'
  get 'products/suggest' => 'products#suggest', :as => 'product_suggest'
  get 'shimano-shop' => 'stores#index', :as => 'store_locator'
  get 'shimano-shop/suggest' => 'stores#suggest', :as => 'store_suggest'
  get 'shimano-shop/regions' => 'stores#regions', :as => 'store_locator_regions'
  get 'shimano-shop/provinces' => 'stores#provinces', :as => 'store_locator_provinces'
  get 'shimano-shop/cities' => 'stores#cities', :as => 'store_locator_cities'
  get 'shimano-shop/:specialist' => 'stores#specialist'
  get 'cataloghi-shimano' => 'press#index'
  get 'concorso' => 'contests#home'
  get 'concorso/gioca' => 'contests#play'
  get 'concorso/gioca/risultato' => 'contests#result'
  get 'concorso/premi' => 'contests#prizes'
  get '/product_list' => 'products#list'
  get '/products_dealers' => 'products#dealer'
  get '/green-line'      => 'contests#index', as: :contest
  get '/green-line/:id'      => 'contests#vote'
  get '/blog' => 'posts#index'
  scope '/blog' do 
    get '/category/:slug' => 'posts#category'
    get '/tag/:url' => 'posts#tag'
    get '/:date/:title' => 'posts#show', :as => :post_show
    get '/:year/:day/:month/:title' => 'posts#show'
  end
  scope '/community' do
    get '/' => 'communities#index', :as => :community
    get '/riserva' => 'events#reserve', :as => :reserve
    scope '/eventi' do
      get '/' => 'events#index', :as => :events
      get '/archive' => 'events#archive', :as => :events_archive
      get '/(:title)--(:id)' => 'events#show', :as => :event
      get '/(:title)--(:id)/list' => 'events#list', :as => :event_list
      get '/(:title)--(:id)/attend' => 'events#attend', :as => :attend_event
    end
    scope '/galleria' do
      get '/' => 'galleries#index', :as => :galleries
      get '/:id' => 'galleries#show', :as => :gallery
      get '/:gallery_id/foto/:id' => 'photos#show', :as => :photo
      post '/:gallery_id/photos/:id' => 'photos#like', :as => :like_photo
    end
    scope '/galleries' do
      match "/", to: redirect('/galleria')
      match "/:id", to: redirect('/%{id}')
      match '/:gallery_id/photo/:id', to: redirect('/%{gallery_id}/foto/%{id}')
    end
  end

  match '/community/ask-shimano', to: redirect('/ask-shimano'), :status => 301
  match '/community/ask-shimano/*params', to: redirect {|params| "/ask-shimano/#{CGI::unescape(params[:params])}" }, :status => 301

  scope '/garanzia/ask-shimano' do

   
      get '/' => 'question_categories#index', :as => :ask_shimano
      get '/mondo-artificiali/(*params)', to: redirect {|params| "/ask-shimano/tecniche-e-attrezzatura/#{CGI::unescape(params[:params])}" }, :status => 301
      get '/attrezzatura/(*params)', to: redirect {|params| "/ask-shimano/tecniche-e-attrezzatura/#{CGI::unescape(params[:params])}" }, :status => 301
      get '/tecniche-di-pesca/(*params)', to: redirect {|params| "/ask-shimano/tecniche-e-attrezzatura/#{CGI::unescape(params[:params])}" }, :status => 301
      get '/search' => 'questions#search', :as => :search_questions_path
      get '/:category_url(/:subcategory_url)' => 'questions#index', :as => :questions
      get '/:category_url/new-question/expert' => 'questions#expert', :as => :new_expert
      get '/:category_url(/:subcategory_url/)new-question/' => 'questions#new', :as => :new_question
      post '/:category_url' => 'questions#create'
      get '/:category_url/:subcategory_url/:id' => 'questions#show', :as => :question
      post '/:category_url/:subcategory_url/:id/like-answer/:answer_id' => 'questions#like_answer', :as => :like_question_answer
      post '/:category_url/:subcategory_url/:id/send-answer' => 'questions#create_answer', :as => :question_answer
  end

  

  match "/catalogo", to: redirect('/attrezzatura-pesca')
  match "/cataloghi", to: redirect('/cataloghi-shimano')

  scope '/catalogo' do
    match "/", to: redirect('/attrezzatura-pesca')
    match '/:product_type/', to: redirect('/attrezzatura-pesca/%{product_type}')
    match '/:product_type/:product_family', to: redirect('/attrezzatura-pesca/%{product_type}/%{product_family}/')
    match '/:product_type/:product_family/:product_url', to: redirect('/attrezzatura-pesca/%{product_type}--%{product_url}/')
    get '/:product_type/:product_family/tags/(*tags)', to: redirect("/attrezzatura-pesca/%{product_type}/%{product_family}/tags/%{tags}")
  end

  get '/dealers' => 'dealers#index'
  get '/dealers/new' => 'dealers#new'
  get '/dealers/:id' => 'dealers#show'
  post '/dealers/new' => 'dealers#create', as: :dealer_assistance_requests

  match "/attrezzatura-pesca" => 'product_finder#index'

  scope '/attrezzatura-pesca' do
    get '/trova/' => 'product_finder#index'
    get '/trova/*slug' => 'product_finder#index'
    get '/*das', to: redirect('/attrezzatura-pesca')
  end

  get '/tags' => 'tags#index'
  get '/posttags' => 'post_tags#index'

  scope "/garanzia"  do

    devise_for :fishers, :path => '', :skip => [:registrations], :controllers => { :sessions => 'fishing_club/sessions', :confirmations => 'fishing_club/confirmations', :passwords => 'fishing_club/passwords'}
    devise_scope :fisher do
    get 'pro-staff' => 'prostaff#index', :as =>   'pro_staff'
    get 'pro-staff/:url' => 'prostaff#show', :as => 'show_pro_staff'
    get 'prodotti' => 'fishing_club/fishing_club#product'
    get 'eventi' => 'fishing_club/fishing_club#events'
    get "modifica-dati-personali" => "fishing_club/registrations#edit", :as => 'edit_fisher_registration'
      get "cancella" => "fishing_club/registrations#cancel", :as => 'cancel_fisher_registration'
      delete "cancella-iscrizione" => 'fishing_club/registrations#destroy', :as => 'destroy_fisher_registration'
      post "/" => "fishing_club/registrations#create", :as => 'fisher_registration'
      put "/" => "fishing_club/registrations#update"
      post "/" => "fishing_club/registrations#destroy"
      get "registrati" => "fishing_club/registrations#new", :as => 'new_fisher_registration'
    end
    resources :photos, :controller => 'fishing_club/photos', :only => [:new, :create]
    resources :product_registrations, :controller => 'fishing_club/product_registrations', :only => [:index, :new, :create, :show, :update, :edit] do
      collection do
        post 'confirm'
      end
    end
    get '/' => 'fishing_club/fishing_club#index', :as => 'fishing_club'
  end

  get '/:page' => 'pages#show'

end

app/models/store.rb
class Store < ActiveRecord::Base
  validates :name, :address, :region, 
            :province, :city, :cap, 
            :phone, :presence => true
  
  has_many :product_registrations, :dependent => :destroy

  after_validation :set_visiblility
  
  scope :visible, where(:hidden => false)
  
  before_validation :generate_country

  serialize :geo_data
  
  def lat_lng
      if geo_data.present?
        geo_data.first["geometry"]["location"]
      end
  end

  def self.update_from_csv
    require 'csv'    
    #206868,"RENZI LINO, DOGANA REP. SAN MARINO",VIA 3  SETTEMBRE N 126,47891,DOGANA REP. SAN MARINO,EE ,renzicacciapesca@alice.sm  
    csv_text = File.read('stores.csv')
    csv = CSV.parse(csv_text, :headers => false)
    no_data = []
    csv.each do |row|
      cap = row[3].strip
      email = row[6].strip
      sname = row[1].downcase
      saddress = row[2].downcase
      s = Store.where(cap: row[3])
      if s.count == 1 
        s.first.reserve = true
        s.first.email = email
        s.first.save
      else
        no_data << row[1]
      end
    end
    puts no_data
  end

  def nice_url
    unless self.website[/\Ahttp:\/\//] || self.website[/\Ahttps:\/\//]
      "http://#{self.website}"
    else
      self.website
    end
  end

  def self.exportable_attributes
    self.column_names.select{|name| not name =~ /(updated|created)_at/}
  end
  
  def self.regions
    self.uniq.pluck(:region)
  end          
  
  def self.cities(region = nil, province = nil)
    self.uniq.select(:city).where(:province => province, :region => region).map(&:city)
  end
  
  def self.provinces(region = nil)
    self.uniq.select(:province).where(:region => region).map(&:province)
  end
  
  def complete_address
    "#{self.address}, #{self.cap} #{self.city} - #{self.province}"
  end

  def half_address
    "#{self.cap} #{self.city} - #{self.province}"
  end

  def expert
    self.boat || self.bass || self.surf || self.spinningsw || self.spinningfw || self.pesca_al_colpo || self.carpfishing || self.trota_lago
  end
  
  def to_s
    "#{self.name} - #{self.complete_address}".strip
  end
  
  def gmaps_address
    "#{self.address}, #{self.city}, #{self.cap}, Italy"
  end

  def generate_country
    if self.address.present?
      address = URI.encode("#{self.address} + #{self.city}")
      result = JSON.load(open("https://maps.googleapis.com/maps/api/geocode/json?address=#{address}&key=AIzaSyAD-8y-r80aw9kMjNARzKgvhb5LBHhk-Y8"))
      puts result
      if result["results"].present?
        self.geo_data = result["results"]
       else
        self.geo_data = nil
      end
    end
  end
  
  protected
    def set_visiblility
      self.hidden = false if self.hidden.nil?
    end  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :fix_params
  respond_to :html, :json
  def index
    @regions = get_regions
    @regions = @regions.uniq.sort
    @provinces = get_provinces(params[:store][:region])
    @provinces  = @provinces.uniq.sort
    @cities = get_cities(params[:store][:region], params[:store][:province])
    @cities = @cities.uniq.sort
    if params[:specialist]
    @stores = get_special_stores(params[:store])
    else
    @stores = get_stores(params[:store])
    end
    @page_title = "Shimano shop"
    @meta_description = "Trova il negozio Shimano Shop piu vicino a te e specializzato nella vendita di prodotti per la pesca"
      if params[:store][:region].present?
        @page_title = "Shimano shop in " + params[:store][:region]
        @meta_description = "Trova il negozio Shimano Shop in" + params[:store][:region]
      end
      if params[:store][:city].present?
        @page_title = "Shimano shop a " + params[:store][:city]
        @meta_description = "Trova il negozio Shimano Shop a" + params[:store][:city]
      end
  end
  def suggest
    stores = Store.arel_table
    @stores = Store.visible.where(stores[:name].matches("%#{params[:term]}%"))
  end
  
  def get_regions
    Store.visible.regions.collect{|region| region.titleize}
  end
  
  def get_provinces(region)
    Store.visible.provinces(region)
  end
  
  def get_cities(region, province)
    Store.visible.cities(region, province)
  end

   def get_sregions
    Store.visible.where(params[:specialist]).regions.collect{|region| region.titleize}
  end
  
  def get_sprovinces(region)
    Store.visible.where(params[:specialist]).provinces(region)
  end
  
  def get_scities(region, province)
    Store.where(params[:specialist]).visible.cities(region, province)
  end
  
  protected
    
    def get_stores(options = {})
      return Store.visible.where(options).order("region ASC, province ASC, name ASC").paginate(:per_page => 20, :page => params[:page]) || []
    end

    def get_special_stores(options = {})
      return Store.where(params[:specialist]).where(options).order("region ASC, province ASC, name ASC").paginate(:per_page => 20, :page => params[:page]) || []
    end

  
    def fix_params
      params[:store] ||= {}
      params[:store] = params[:store].select{|k,v| v.present? }
    end
end

app/views/stores/index.html.erb
<div id="store" class="container">
  <div class="row header">
    <div class="col span_5"><h1><strong>Shimano</strong> store locator</h1><p>Trova lo Shimano Shop più vicino a casa tua !</p></div>
    <div class="col span_7">
      <div class="filters">
        <h2>Filtra per località</h2>
<%= form_for "store", :url => store_locator_path+"#search_stores", :method => :get do |f| %>

<div class="row-fluid">
<div class="span4" style="position:relative;">
 <%= f.select('region', @regions, :selected => params[:store][:region], :include_blank => 'Tutte le regioni', :class => "myclass")%>
</div>
  <% unless @provinces.empty? %>
  <div class="span4" style="position:relative;">
  <%= f.select('province', @provinces, :selected => params[:store][:province], :include_blank => 'Tutte le province' )%>
</div>
  <% end %>
  <% unless @cities.empty? %>
  <div class="span4" style="position:relative;">
  <%= f.select('city', @cities, :selected => params[:store][:city], :include_blank => 'Tutte le città' )%>
</div>
  <% end %>
<% end %>
</div>
</div>
<div class="filters">
  <h2>Filtra per Shimano Specialist</h2>
  <% if @stores.select{ |store| store.x_store == true }.count > 0 %>
<a href="<%= url_for(params.merge({:specialist => 'x_store'})) %>" class="specialist swb" data-toggle="tooltip" title="X-Store">
<span>xs</span></a>  <% end %>
  <% if @stores.select{ |store| store.tech == true }.count > 0 %>
<a href="<%= url_for(params.merge({:specialist => 'tech'})) %>" class="specialist bbf" data-toggle="tooltip" title="Tech">
<span>TEC</span></a>
<% end %>

</div>
    </div>
  </div>
  <% unless @stores.empty? %>

  <% @stores.each_slice(4) do |slice| %>
  <div class="row stores">
 <% slice.each do |store| %>
<div class="col span_3">
      <div class="store">
        <h2><%= store.name %></h2>
        <p><%= store.address %><br>
          <%= store.half_address %><br>
          <%= store.phone %><br>
          <%= link_to "Visita il sito", store.website, :target => "_blank" if store.website.present? %></p>
          <div class="specialist">
            <% if store.x_store %>
<a href="/shimano-shop?specialist=x_store" class="specialist swb" data-toggle="tooltip" title="X-Store"><span>XS</span></a>
<% end %>
<% if store.tech %>
<a href="/shimano-shop?specialist=tech" class="specialist bbf" data-toggle="tooltip" title="Tech"><span>TEC</span></a>
<% end %>
          </div>
          <a href="https://www.google.it/maps/search/<%= store.address.parameterize(sep = '+')%>+<%= store.half_address.gsub('-','').parameterize(sep = '+') %>" target="_blank" class="btn grey storelink"><%= fa_icon "map-marker" %>  Google Map</a>
      </div>
</div>
<% end %>
</div>
<% end %>
<%= will_paginate @stores, :next_label => 'Succ.', :previous_label => 'Prec.' %>
<% end %>
</div>

app/views/stores/specialist.html.erb
<img src="/head_<%= params[:specialist] %>.jpg" alt="">
<h2>Shimano <%= I18n.t("specialist.#{@specialist}.title") %> specialist</h2>
<p>__</p>
<p> <%= I18n.t("specialist.#{@specialist}.description") %></p>
<div id="search_stores">
<%= form_for "store", :url => store_locator_path+"/#{@specialist}"+"/#search_stores", :method => :get do |f| %>

<div class="row-fluid">
<div class="span4" style="position:relative;">
 <%= f.select('region', @regions, :selected => params[:store][:region], :include_blank => 'Tutte le regioni', :class => "myclass")%>
</div>
  <% unless @provinces.empty? %>
  <div class="span4" style="position:relative;">
  <%= f.select('province', @provinces, :selected => params[:store][:province], :include_blank => 'Tutte le province' )%>
</div>
  <% end %>
  <% unless @cities.empty? %>
  <div class="span4" style="position:relative;">
  <%= f.select('city', @cities, :selected => params[:store][:city], :include_blank => 'Tutte le città' )%>
</div>
  <% end %>
<% end %>
</div>
</div>
<% unless @stores.empty? %>
<div style="clear:both;"><br></div>
<div id="storebox">

  <% @stores.each_slice(4) do |slice| %>
  <div class="row-fluid storerow">
  <% slice.each do |store| %>
  <div class="span3"><%= render_store(store) %>
   
    </div>
  <% end %>
</div>
<%end %>
<div style="clear:both;"></div>
</div>
<%= will_paginate @stores, :renderer => BootstrapPagination::Rails, :next_label => 'Succ.', :previous_label => 'Prec.' %>
<% end %>